---
- name: Configure EC2 instance
  hosts: web_server
  become: yes
  vars:
    docker_version: "20.10.7"
    app_env: "production"
    app_secret: "my_secret_key"  # Use Ansible Vault in production
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce={{ docker_version }}
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker container
      docker_container:
        name: myapp
        image: myusername/myapp:latest  # Replace with your DockerHub repo
        state: started
        restart_policy: always
        ports:
          - "80:80"
        env:
          APP_ENV: "{{ app_env }}"
          APP_SECRET: "{{ app_secret }}"
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "3"
